name: Build CPU Gaming

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build in Release mode
        run: dotnet build --configuration Release --no-restore

      - name: Publish (Self-Contained)
        run: dotnet publish -c Release -r win-x64 --self-contained false -o ./publish

      - name: Create ZIP for Release
        run: Compress-Archive -Path ./publish/* -DestinationPath CPU_Gaming.zip

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CPU_Gaming
          path: CPU_Gaming.zip
